### ISSUE TITLE
ButtonModel#iconAlign should have a default value or be removed

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui-default#17]
You shouldn't need to specify it as I can't recall a single need for right aligned icons. Actually, I even think that perhaps it should be removed, because the only use case I can see is RTL UI, which is a totally different property.

**Comment by oleq** [comment]
Please note that the feature is required by http://tests.ckeditor.dev:1030/build/amd/tests/theme-lark/manual/theme. So it cannot simply be removed.

**Comment by Reinmar** [comment]
It may be replaced by something more meaningful (like UI's general text dir setting?)... but I don't know yet how it should be generalised, so that's why I'd just make sure that `iconAlign` doesn't spread across our code.

**Comment by oleq** [comment]
AFAIR the problem was also that it was not possible to bind to non-existing model attribute (key). Because of that, if we assumed that by default, all `ButtonView` (also `IconView`) instances have alignment to left when there's no `model.rtl/iconAlign/whatever` set in the model, an error was thrown, because bindings in the `View` (`Template` since https://github.com/ckeditor/ckeditor5-ui/issues/3) expect a bound attribute to exist. So that's why `iconAlign` spread across the project, the original idea was that it exists only when the alignment isn't standard. This is something to look at when addressing this issue.

**Comment by Reinmar** [comment]
> Actually, I even think that perhaps it should be removed, because the only use case I can see is RTL UI, which is a totally different property.

I also checked in CKE4 that you can easily style the icon to appear on the right without changing the DOM. So that model's prop seems even less necessary.
