### ISSUE TITLE
Tests: Shouldn't views be tested totally independently from controllers?

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui-default#26]
Right now (at least in some tests – e.g. button) we create the component by creating its controller and model. Then we change something in the controller's model and check what happened in the view. That's wrong – views should be tested through their models.

**Comment by oleq** [comment]
So instead of 

``` js
    beforeEach( () => {
        model = new Model( {
            label: 'foo',
            isEnabled: true,
            isOn: false
        } );

        view = new ButtonView();

        return new Button( model, view ).init();
    } );
```

it would be

``` js
    beforeEach( () => {
        view = new ButtonView();
        view.model.set(  {
            label: 'foo',
            isEnabled: true,
            isOn: false
        } );

        view.init();
    } );
```

It perfectly makes sense to me.

**Comment by oskarwrobel** [comment]
When we test views independently from controllers, child views placed in collections are not rendered. We might need some tools for mocking views.

E.g: https://github.com/ckeditor/ckeditor5-ui-default/blob/master/tests/labeledinput/labeledinputview.js#L32-L55

**Comment by Reinmar** [comment]
Not valid after controllers were removed.

**Comment by fredck** [comment]
As an outsider comment, your resolution to this issue doesn't reflect your intentions when you opened the issue. It's not about having a controller class or not. This is actually irrelevant.  It's about the right way to test views, which should be done by manipulating their models.

If the above is how we ended up doing it, then ofc this issue is to be closed as "fixed". Otherwise you may think whether it should still be open.

**Comment by Reinmar** [comment]
We always tested views by changing their models, but previously we were changing the intermediate component models. Those models are totally gone now so this is invalid.
