### ISSUE TITLE
ButtonMode.noText -> withText

### ISSUE THREAD

**Issue by Reinmar** [ckeditor/ckeditor5-ui-default#30]
By default you'd like to have a button without a text and passing `noText` everywhere isn't nice.

**Comment by oskarwrobel** [comment]
Do we want to keep `.ck-button-notext` class and toggle it depends on `withText` option? Or we want to change `.ck-button-notext` to `.ck-button-withtext` and hide label in CSS at default?

//cc: @oleq

**Comment by oleq** [comment]
Since we assume that text–less button will be the common case, it should be as simple as possible, which means no attribute in the model and no specific class in DOM.

So, let's create an attribute like `withText` or `showText` and corresponding class `"ck-button-with-text"` or `"ck-button-show-text"`. Or maybe simply `text` and `"ck-button-text"`? OTOH the last one may be confusing  because it suggests the actual text content in the model. WDYT?

**Comment by oskarwrobel** [comment]
I've created attribute `withText` and text for buttons is hidden at default, also for buttons inside dropdowns. We might consider of setting `withText` as true for dropdown buttons.

**Comment by Reinmar** [comment]
Hm... that's an interesting question.

Do dropdowns with icons only make sense? I think so, so this needs to stay configurable in dropdown models.

So the question is whether the default value should be true or false. I think it can stay false, so we always need to set `withText: true` for dropdowns. Otherwise, we may make it confusing that for buttons you may specify `withText: true`, but for dropdowns you use `withText: false` (you only use the option to change the default behaviour).

WDYT?

**Comment by oleq** [comment]
> Do dropdowns with icons only make sense? I think so, so this needs to stay configurable in dropdown models.

Dropdowns with icons do work. It's the `DropdownButton` which is responsible for rendering the `Icon` (inherits from `Button`):

![image](https://cloud.githubusercontent.com/assets/1099479/16917978/1c995cfa-4d04-11e6-92ac-40e738a85a34.png)

![image](https://cloud.githubusercontent.com/assets/1099479/16918052/5ebe4172-4d04-11e6-8201-289e2866b938.png)

At the moment the feature isn't enabled because there was no such need so far. It's a matter of binding two attributes from `ButtonModel` to `DropdownModel`, a one–liner.

> So the question is whether the default value should be true or false. I think it can stay false, so we always need to set withText: true for dropdowns.

I think that as long as `Dropdown` utilises `Button`, the `ButtonModel` interface must be preserved. IMO it's not a big deal that `withText` attribute must be specified.

However if we decided to hack it, I'd rather make `withText: true` default for `DropdownModel` somehow. OTOH, it would mean that the `Controller` extends the `Model` it has received from the outside, which is an anti–pattern.

**Comment by Reinmar** [comment]
> However if we decided to hack it, I'd rather make withText: true default for DropdownModel somehow. OTOH, it would mean that the Controller extends the Model it has received from the outside, which is an anti–pattern.

First of all – [button gets its own model](https://github.com/ckeditor/ckeditor5-ui-default/blob/0f66c32fbf654978fc4fcd7aa94f0353b93257f3/src/dropdown/dropdown.js#L61-L63):

``` js
        // Button needs a separate Model because otherwise it would fire #execute event
        // on the model shared between multiple dropdowns (they would all open at the same time).
        buttonModel.bind( 'label', 'isOn', 'isEnabled' ).to( model );
```

so there's no need in hacking anything.

But most importantly, IMO, it's not that important to set it to true by default in this case. Dropdown is just a special kind of button, so let it have the same API. In CKE4 dropdowns had only text, while no one said that it's the best option. The best option is to have the same options which all other buttons have.

**Comment by oleq** [comment]
So the conclusion is that https://github.com/ckeditor/ckeditor5-headings/pull/15 was valid, right? 😄

**Comment by Reinmar** [comment]
Yep. It only lacked a ticket.

**Comment by oleq** [comment]
I decided that this one last time PRs will get milestone instead of tickets.
