### ISSUE TITLE
Form component

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#54]
See https://github.com/ckeditor/ckeditor5-link/issues/16

**Comment by Reinmar** [comment]
I'm looking now at https://github.com/ckeditor/ckeditor5-link/blob/t/2/src/ui/linkballoonpanel.js and what I feel is that there's a lot of code which will repeat in every possible form. All those private functions do a lot of things which we'll be able to simplify through helpers. So once we'll see that some other type of forms (in other features) require similar pieces, we should move "helperise" them.

**Comment by oskarwrobel** [comment]
I'm wondering (It might have no sense :P) if is it possible to make`Form` not as a component but as a mixin?

Most of components with inputs will need to create a proxy `Form` component. E.g

```
<LinkBalloonPanelComponent>
    <FormComponent>
        <content region>
    </FormComponent>
</LinkBalloonPanelComponent>
```

I'm wondering if is it possible to do something like this:

```
class LinkBalloonPanel extends BalloonPanel {
    constructor() {
        mix( this, formMixin )
    }
}

class LinkBalloonPanelView extends BalloonPanelView {
    constructor() {
        Template.extend( this.template, {
            tag: 'form'
        }

        mix( this, formViewMixin );
    }
}
```

**Comment by Reinmar** [comment]
Interesting idea. It's often better to mix things rather than depend on inheritance. If we see that we cannot define a base form class or that it doesn't represent anything, then a mixin would be the way to go. But it may also turn out that all features need the same type of form component, or that specialised classes are fully sufficient and then it would be an easier way to go.

**Comment by oleq** [comment]
Closed in https://github.com/ckeditor/ckeditor5-ui-default/issues/60.
