### ISSUE TITLE
How to deal with forms in other components?

### ISSUE THREAD

**Issue by oleq** [ckeditor/ckeditor5-ui-default#67]
A followup of the discussion in https://github.com/ckeditor/ckeditor5-ui-default/issues/54.
1. Do we really need form component? ATM it brings `submit` event only, which could be handled by us, but obscures the UI controller tree, which is IMO not quite necessary, at least at this stage of the project.
2. If we go with form, how to implement it? As [some sort of mixin like @oskarwrobel suggested](https://github.com/ckeditor/ckeditor5-ui-default/issues/54#issuecomment-245301042)? As a standalone component (which it is now)?
3. What other benefits could using `<form>` bring to the project? Better accessibility? Enhanced tab–key navigation management?
4. How to deal with form action buttons like OK, Close, etc.? Should they belong to the form (be spawned and managed by it) or injected from the parent component, like the balloon panel (current implementation)?

**Comment by Reinmar** [comment]
My POV.

## DOM perspective

Quote from the [spec](https://www.w3.org/TR/html5/forms.html#the-form-element) (emphasis is mine):

> The form element represents a collection of form-associated elements, some of which can represent editable values that **can be submitted to a server for processing**.

So, it seems for me that our forms should not use the `<form>` elements. I also don't see any forms in CKE4.

## Theming perspective

AFAIU, each input, input with a label, or a button is styled as a separate component. So those fields don't need any grouping (container with a class) in order to be styled at all.

However, some layouts will require additional containers in order to correctly position things. So in a panel which contains a form you will need to be able to define few additional elements here and there. Those elements are not components – we shouldn't try to "componetise" every possible element in the DOM, because it's crazy (code size and maintenance wise).

## Using components in a template

Since we should not create components and regions for every piece of a DOM where we need to use another component, there needs to be an easy way to mix components with templates. This is something that I had in mind for a long time, but what stood in contradiction (or at least wasn't super compatible) with the idea of regions which was born before I joined CKE5 UI lib project. It's pretty clear now that we miss such a feature pretty badly.

So, we have a `BalloonPanel` with `BalloonPanelView`. We want to use that component to display a form (in the "set of inputs and buttons" meaning) inside it. Let's say that `BalloonPanelView` defines a region for its content (that makes sense).

Now, we've got the `Link` feature class which should glue all the pieces:
1. It needs to create a balloon instance.
2. It needs to create a link form instance.
   - the form needs to have input components inside,
   - it should also have buttons,
   - and finally, it should let us know once the whole thing is submitted (more about this later).
3. Finally, it needs to insert the link form inside the balloon and the balloon to editor UI's body region.

Part of the `Link` (feature) class:

``` js
createBalloon() {
    const editor = this.editor;

    const balloon = new Balloon( balloonModel, new BalloonView( editor.locale ) );
    const linkForm = new LinkForm( linkFormModel, new LinkFormView( editor.locale ) );

    balloon.add( 'contents', linkForm );
    editor.ui.add( 'body', balloon );
}
```

The `LinkFormView` constructor:

``` js
constructor( locale ) {
    super( locale );

    this.template = new Template( {
        tag: 'div',
        attributes: [
            class: [ 'ck-link-form' ]
        ],
        children: [
            < URL input+label >,
            {
                tag: 'div',
                attributes: {
                    // BTW. I still find it super annoying that I have to define the attributes
                    // property every time I want to set a simple class!
                    class: [ 'ck-link-form-footer' ]
                },
                children: [
                    < OK button >,
                    < Cancel button >
                ]
            },
            < Unlink button > // Let's say it needs to be here.
        ]
    } );
}
```

Now, we need to answer where to get those buttons and input from. Also, we need to understand how a 3 different `Button`s can be created for this use (because [this](https://github.com/ckeditor/ckeditor5-link/blob/82345cfe6f05d1ac6a4923ffc23fc6ebf48b821d/src/ui/linkballoonpanel.js#L138) means that `LinkBalloonPanelView` doesn't control how the button looks).

So, a `LinkFormView` can choose which views to use. In order to instantiate views we only need the locale, so the view will be able to instantiate it child views.

However, the `LinkForm` controller needs to be able to instantiate proper controllers for those child views. Hence, those views need to be exposed in some way. Let's consider the simplest possible way – as view instance properties:

``` js
constructor( locale ) {
    super( locale );

    // TODO we still need to specialise those buttons (their type).
    this.okButton = new ButtonView( locale );
    this.cancelButton = new ButtonView( locale );
    this.unlinkButton = new ButtonView( locale );
    this.urlInput = new LabeledInputView( locale );

    this.template = new Template( {
        tag: 'div',
        attributes: [
            class: [ 'ck-link-form' ]
        ],
        children: [
            this.urlInput,
            {
                tag: 'div',
                attributes: {
                    class: [ 'ck-link-form-footer' ]
                },
                children: [
                    this.okButton,
                    this.unlinkButton
                ]
            },
            this.unlinkButton
        ]
    } );
}
```

And not let's look back into the `Link` feature:

``` js
createBalloon() {
    const editor = this.editor;

    const balloon = new Balloon( balloonModel, new BalloonView( editor.locale ) );
    const linkForm = new LinkForm( linkFormModel, new LinkFormView( editor.locale ) );

    new Button( okButtonModel, linkForm.okButton );
    new Button( cancelButtonModel, linkForm.cancelButton );
    new Button( unlinkButtonModel, linkForm.unlinkButton );
    new LabeledInput( urlInputModel, linkForm.urlInput );

    balloon.add( 'contents', linkForm );
    editor.ui.add( 'body', balloon );
}
```

What's still missing is a `LinkForm`'s knowledge about its children so it can destroy them properly. We have the `Controller.add( regionName, controller )` method, and since we don't have a region name in this case we could agree on anonymous regions for this case:

``` js
linkForm.add( new Button( okButtonModel, linkForm.okButton ) )
linkForm.add( new Button( cancelButtonModel, linkForm.cancelButton ) );
linkForm.add( new Button( unlinkButtonModel, linkForm.unlinkButton ) );
linkForm.add( new LabeledInput( urlInputModel, linkForm.urlInput ) );
```

Hopefully I didn't miss anything, because this even look pretty smooth. We should be able to achieve this without touching too much and the new addition seem to be pretty flexible. For instance, if a parent view knows everything about its child it can create that child's model itself.

## Specialising buttons

So, as I mentioned above, [this](https://github.com/ckeditor/ckeditor5-link/blob/82345cfe6f05d1ac6a4923ffc23fc6ebf48b821d/src/ui/linkballoonpanel.js#L138) is wrong, because then you cannot replace the `ButtonView` with `MyBootstrapButtonView`. The type of a button must be passed to the button through a model (it's a view's job to then render the correct classes) and we could have few specialised `ButtonView`s, but that doesn't seem to be necessary if we add a type to the model.

## Form controller

That's the last topic. Do we need a specialised controller and view for forms?

There are two form-related behaviours which will repeat:
- Focus control.
- Submition control.

Both aspects are touching view related logic, so I think that, in our case, it should be kept in the `LinkFormView`. However, the logic will of course repeat, so we'll need tool(s) for it. E.g., we can add this to to the `LinkFormView#constructor`:

``` js
constructor( locale ) {
    // ...

    this.formController = new FormController();

    this.formController.addFocusable(
        this.urlInput,
        this.okButton,
        this.cancelButton,
        this.unlinkButton
    );

    this.formController.delegate( 'submit' ).to( this.model ); // We can expose the submit.
}

destroy() {
    super();
    this.formController.destroy();
}
```

Ofc, the above is just an idea how the API might look like. It can also be extended with some space for validation messages and whatever comes to my mind.

OK... how do you feel about this :D

**Comment by oleq** [comment]
> OK... how do you feel about this :D

I haven't read this yet but I'm overwhelmed :D

**Comment by oskarwrobel** [comment]
> So, it seems for me that our forms should not use the form elements. I also don't see any forms in CKE4.

We definitely can live without `<form>` element, but it's helpful wen you want to support submit on <kbd>Enter</kbd> press. Without `<form>` element you need to listen `KeyboardEvent` on each form field, besides that you need to listen `click` on each submit button. With `form` element there is only one listener.

**Comment by Reinmar** [comment]
> > So, it seems for me that our forms should not use the form elements. I also don't see any forms in CKE4.
> 
> We definitely can live without <form> element, but it's helpful wen you want to support submit on Enter press. Without <form> element you need to listen KeyboardEvent on each form field, besides that you need to listen click on each submit button. With form element there is only one listener.

I know. But that's what the form controller could do automatically with fields which are registered to it.

**Comment by pjasiun** [comment]
In general, I agree with the proposal. My only doubt is about the way you add not named and  named regions.

Not named nested view is added as an object inside the template (according to the proposal). At the same time named nested view (a.k.a. named region) is added below the template definition. The API to get such element is different too: one you get by name the other by reference. Also, named regions handle only collections and not-named only single element.

Another problem is that you can not pass parameters to the nested element in the template. Sure, you can do it in the constructor, but then you do not have them in the strange order, the code is not nice to read.

So my proposal is to treat nested views and collection the same way, more less like custom HTML elements:

``` js
constructor( locale ) {
    super( locale );

    this.template = new Template( {
        tag: 'div',
        children: [
            {
                type: ButtonView,
                attributes: {
                    class: [ 'ck-button-red' ],
                    customAttribute: 'x'
                }
            },
            {
                type: CollectionView,
                attributes: {
                    class: [ 'ck-footer' ]
                }
            },
            {
                // type: ElementView - default
                tag: 'div',
                attributes: {
                    class: [ 'ck-link-form-footer' ]
                },
                children: [
                    this.okButton,
                    this.unlinkButton
                ]
            }
        ]
    } );
}
```

`ButtonView` get all attributes in the constructor an can do with it whatever it needs.

Then the question is how to provide access to these nested properties. See two ways:
- get them by class, like we do with regions now,
- add `name`, `propertyName`, 'bind' property or use `bind.to`.

**Comment by pjasiun** [comment]
Also, if you can create the whole `View` passing the template I would consider giving the option to create a `View` from the controller directly, without a need to create a special class for each view.

**Comment by Reinmar** [comment]
It's an interesting idea. But:
1. The `type: ButtonView` + attributes will be problematic to implement, because each view will have to accept attributes in its constructors (and do something with them). And what about other bindings and, actually, the whole model? Properties of instance of that view must be bound to something which wouldn't be possible in the way you proposed.
2. In what element the `CollectionView` would be rendered? `div`? `span`?

So, I think that while interesting, this idea went too far. But I'd borrow from you the idea to define collections differently than before. They should be as usable as instances of other views (e.g. `this.okButton` from the example above):

``` js
constructor( locale ) {
    super( locale );

    this.okButton = ...;
    this.unlinkButton = ...;
    this.someCollection = new ViewCollection( ... );

    this.template = new Template( {
        tag: 'div',
        children: [
            {
                tag: 'div',
                attributes: {
                    class: [ 'ck-footer' ]
                },
                children: [
                    this.someCollection
                ]
            },
            {
                tag: 'div',
                attributes: {
                    class: [ 'ck-link-form-footer' ]
                },
                children: [
                    this.okButton,
                    this.unlinkButton
                ]
            }
        ]
    } );
}
```

**Comment by Reinmar** [comment]
In other words – we must work with instances of views and collections, not with "types".

**Comment by oleq** [comment]
Just to not to forget (possible followups):
- If https://github.com/ckeditor/ckeditor5-ui/issues/88 and https://github.com/ckeditor/ckeditor5-link/issues/54 are OK, then we should get rid of the `Form` component.
- Other components should also benefit from the new API.

**Comment by Reinmar** [comment]
Did you also try to check how other components in the `ui-default` will be able to look like?

**Comment by oleq** [comment]
Yes, the first one to change is `LabeledInput`. Perhaps others will also benefit. I'll not spend much time on it before the API is accepted in PRs (not necessarily merged).

**Comment by Reinmar** [comment]
But do we know whether it will work for the other components? I understand that you don't want to refactor them before we accept the API, but perhaps we could have a PoC?

**Comment by oleq** [comment]
Yep, I can create some PoCs.
