### ISSUE TITLE
Some easy way of creating component instances

### ISSUE THREAD

**Issue by oskarwrobel** [ckeditor/ckeditor5-ui-default#99]
Right now the way of creating components looks quite complicated. E.g `Button` component - we need to import 3 classes, initialize them and delegate event:

``` javascript
import Model from './model.js';
import Button from './button.js';
import ButtonView from './buttonView.js';

const buttonModel = new Model( {
  foo: 'bar'
} );

buttonModel.on( 'execute', () => // do sth );

const button = new Button( buttonModel, new ButtonView() );
```

I'm thinking about some simplest way as:

``` javascript
import SomeTypeOfButton from './somebutton.js'

const button = new SomeTypeOfButton( {
  foo: 'bar',
  onExecute: () => // do sth
} );
```

or

``` javascript
import Button from './button.js'

const button = Button.create( {
  foo: 'bar',
  onExecute: () => // do sth
} );
```

or

``` javascript
import buttonCreateator from './buttoncreator.js'

const button = buttonCreateator( {
  foo: 'bar',
  onExecute: () => // do sth
} );
```

WDYT?

**Comment by Reinmar** [comment]
Haha, just wanted to create a ticket about the same :D.

I'm not sure though which option is best, tough. Creator should be most flexible but we won't have creators for all of the components, so the experience will be very mixed.

`Button.create()` on the other hand would be a bad idea because then the module which defines it will have a hardcoded view class (so if you'd never use the `Button` with `ButtonView` you'd have the view bundled anyway).

So it seems that creator functions (`createButton()`) would be most reasonable. But I feel that it perhaps require a bigger plan to make all `ui-default/bindings/` functions. Either behaviour handlers or creators.

**Comment by Reinmar** [comment]
I guess we took care of most of ths in #95 and related ticktes.
